khofo/apps/products/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

app_name = 'products'
urlpatterns = [
    path('category/<int:pk>/', views.CategoryListView.as_view(), name="category"),
    path('category/<int:pk>/subcategory/<int:spk>/products/', views.ProductsList.as_view(), name="sub_category"),
    path('category/<int:pk>/subcategoryrow/<int:spk>/products/', views.ProductsListRow.as_view(),
         name="sub_category_row"),
    path('product/<int:pk>/', views.ProductDetails.as_view(), name="product_details"),
    path('reviews/<int:pk>/', views.ProductReview.as_view(), name="product_review"),
    path('productSearch/', views.ProductSearchListView.as_view(), name="product_search_results"),
    # AJAX
    # ----------------------------------------------------------------------------------------------
    path('ajax/recentviewed/', views.show_recent, name='show_recent'),
    path('ajax/getsubcategoryid/', views.get_sub_category_id),
    path('ajax/check_filter/', views.check_filter),
    path('ajax/delete_selection/', views.delete_selection, name='delete_selection'),
    path('ajax/search/', views.product_search),

]

khofo/config/urls.py
# Django
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.static import serve
# Views
from apps.products import views as product_view
from apps.advertisement import views as ads_view
from apps.user import views as clint_views
from apps.support import views as support_view

urlpatterns = [
    path('jet/', include('jet.urls', 'jet')),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    #################################################################################

]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('', product_view.CategoriesListView.as_view(), name="home"),
    # path('paypal/', include('paypal.standard.ipn.urls')),
    path('home/', product_view.CategoriesListView.as_view(), name="home"),
    path('user/', include('apps.user.urls')),
    path('productHome/', include('apps.products.urls')),
    path('order/', include('apps.orders.urls')),
    path('shipping/', include('apps.shippings.urls')),
    path('ads/', include('apps.advertisement.urls')),
    path('logout/', clint_views.client_logout, name="logout"),
    path('chaining/', include('smart_selects.urls')),
    # path('adsManagement/', ads_view.AdsManagement, name="AdsManagement"),
    path('support/', include('apps.support.urls')),
     path('export/', include('apps.export.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    prefix_default_language=False
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    ]

handler400 = 'apps.user.views.handler400'
handler403 = 'apps.user.views.handler403'
handler404 = 'apps.user.views.handler404'
handler500 = 'apps.user.views.handler500'

# Change Admin Site
# admin.site.site_header = "Khufu Admin"
# admin.site.site_title = "Khufu Admin Portal"
# admin.site.index_title = "Welcome to Khufu Portal"

khofo/apps/products/forms.py
from django import forms

khofo/apps/products/views.py
# Python
import bleach
# Django
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import EmailMultiAlternatives, BadHeaderError
from django.core.paginator import Paginator
from django.utils.translation import gettext_lazy as _
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Sum
from django.http import JsonResponse, HttpResponse, HttpResponseRedirect
from django.views.generic import DetailView, ListView
from langdetect import detect
# Models
from ..support.forms import EmailForm
from .models import Product, ProductImage, Category, SubCategory, ProductOffer, SpecName, SpecValue, \
    SpecValueChangeable, Review
from ..orders.models import Order
from ..advertisement import views as ads_view


# Create your views here.

# Views
# -----------------------------------------------------------------------------------

# Index (Home)
class CategoriesListView(ListView):
    template_name = 'index.html'
    context_object_name = 'categories'

    def get_queryset(self):
        categories = Category.objects.filter(is_trashed=False)
        if categories.count() > 0:
            products = Product.objects.filter(category_id__in=categories.values_list('id'), is_trashed=False)
            if products.count() > 0:
                categories = categories.filter(id__in=products.values_list('category_id')).order_by('show_num')
                return categories
        return False

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(CategoriesListView, self).get_context_data()
        category_names = get_all_categories_names()
        current_advers2 = get_current_advertisment(self.request, 'home')
        context.update({
            'catNames': category_names,
            'currentAdvers': current_advers2,
            'pageName': 'home',
        })
        return context


# Page of specific category
class CategoryListView(ListView):
    template_name = 'category.html'
    context_object_name = 'subCategory'

    def get_queryset(self):
        sub_categories = SubCategory.objects.filter(category=self.kwargs['pk'], is_trashed=False)
        if sub_categories.count() > 0:
            products = Product.objects.filter(sub_category_id__in=sub_categories.values_list('id'), is_trashed=False)
            if products.count() > 0:
                sub_categories = sub_categories.filter(id__in=products.values_list('sub_category_id')).order_by(
                    'category')
                return sub_categories
        return False

    def get_context_data(self, **kwargs):
        context = super(CategoryListView, self).get_context_data(**kwargs)
        categories = Category.objects.filter(pk=self.kwargs['pk'], is_trashed=False)
        sub_categories = SubCategory.objects.filter(category=self.kwargs['pk'], is_trashed=False)
        withOff = []
        for sub_category in sub_categories:
            if ProductOffer.objects.filter(sub_category=sub_category, is_trashed=False):
                withOff.append(sub_category)
                # print(withOff)
            else:
                print('Not Exists')
        if len(withOff) > 0:
            context.update({
                'offers': withOff,
            })
        if categories.exists():
            currentAdvers = ads_view.advert(
                request=self.request, pageName=categories[0].name)
            if categories[0].name in self.request.session:
                show_num = self.request.session[categories[0].name]['num']
            else:
                show_num = 0
            currentAdvers2 = ads_view.sortAds(list(currentAdvers), int(show_num))
            context.update({
                'cat': categories,
                'currentAdvers': currentAdvers2,
                'pageName': categories[0].name,
            })
        return context


# products of specific sub_category
class ProductsList(ListView):
    template_name = "sub-category.html"
    context_object_name = "products"

    def get_queryset(self):
        if self.request.method == 'GET':
            item_count = 30
            products = get_product_with_paginator(request=self.request, sub_category_id=self.kwargs['spk'],
                                                  items_count=item_count, order_by_type='show_num')
            sort = self.request.GET.get('sort', None)
            if sort:
                sort = bleach.clean(sort.strip())
                if sort == 'n':
                    products = get_product_with_paginator(request=self.request, sub_category_id=self.kwargs['spk'],
                                                          items_count=item_count, order_by_type='-created_on')
                    return products
                elif sort == 'l':
                    products = get_product_with_paginator(request=self.request, sub_category_id=self.kwargs['spk'],
                                                          items_count=item_count, order_by_type='price')
                    return products
                elif sort == 'h':
                    products = get_product_with_paginator(request=self.request, sub_category_id=self.kwargs['spk'],
                                                          items_count=item_count, order_by_type='-price')
                    return products
            return products

    def get_context_data(self, **kwargs):
        context = super(ProductsList, self).get_context_data(**kwargs)
        offers = ProductOffer.objects.filter(
            sub_category_id=self.kwargs['spk'], is_trashed=False).filter(type=2).filter(showed_in=2)
        sub = SubCategory.objects.filter(id=self.kwargs['spk'], is_trashed=False)
        if offers.exists():
            context.update({'offers': offers, })
        if sub.exists():
            current_advers = ads_view.advert(request=self.request, pageName=sub[0].name)
            # print('current_advers = ', current_advers)
            if sub[0].name in self.request.session:
                show_num = self.request.session[sub[0].name]['num']
            else:
                show_num = 0
            currentAdvers2 = ads_view.sortAds(list(current_advers), int(show_num))
            context.update({
                'currentAdvers': currentAdvers2,
                'pageName': sub[0].name,
            })
        return context


# products of specific sub_category with selection
class ProductsListRow(ListView):
    template_name = "sub-category-row.html"
    context_object_name = "products"

    def get_queryset(self):
        if self.request.method == 'GET':
            products = products_filter(request=self.request,
                                       sub_category_id=self.kwargs['spk'])
            # playing(request=self.request, sub_category_id=self.kwargs['spk'])
            if not products == False:
                paginator = Paginator(products, 10)
                page = self.request.GET.get('page')
                products = paginator.get_page(page)
                # print('products = ', products)
                return products
        products = Product.objects.filter(sub_category_id__exact=self.kwargs['spk'], is_trashed=False).order_by('-id')
        paginator = Paginator(products, 10)
        page = self.request.GET.get('page')
        products = paginator.get_page(page)
        return products

    def get_context_data(self, **kwargs):
        context = super(ProductsListRow, self).get_context_data(**kwargs)
        offers = ProductOffer.objects.filter(
            sub_category_id=self.kwargs['spk'], is_trashed=False).filter(type=2).filter(showed_in=2)
        sub = SubCategory.objects.filter(id=self.kwargs['spk'], is_trashed=False)
        products = Product.objects.filter(
            sub_category_id__exact=self.kwargs['spk'], is_trashed=False)
        if products.exists():
            mini = products.order_by('price').first()
            maxi = products.order_by('price').last()
            context.update({
                'min_price': mini.price,
                'max_price': maxi.price,
            })
        if offers.exists():
            context.update({'offers': offers, })
        spec_names = SpecName.objects.filter(sub_category_id=self.kwargs['spk'], is_trashed=False)
        if spec_names.exists():
            enabled_selection = []
            if 'selection' in self.request.session:
                enabled_selection = self.request.session['selection']
                self.request.session.pop('selection')
                # print("enabled_selection = ", enabled_selection)
            all_specs = {}
            all_specs_ar = {}
            for spec_name in spec_names:
                spec_values = SpecValue.objects.filter(
                    sub_category_id=self.kwargs['spk'], spec_name=spec_name, is_trashed=False).distinct('spec_value')
                # print('spec_values = ', spec_values)
                values = [spec_value for spec_value in spec_values]
                all_specs.update({
                    str(spec_name.spec_name): values,
                })
                all_specs_ar.update({
                    str(spec_name.spec_name_ar): values,
                })
            # print("all_specs = ", all_specs)
            # print("all_specs_ar = ", all_specs_ar)
            context.update({
                'spec_names': all_specs,
                'spec_names_ar': all_specs_ar,
                "enabled_selection": enabled_selection,
            })
        if sub.exists():
            current_advers = ads_view.advert(
                request=self.request, pageName=sub[0].name)
            if sub[0].name in self.request.session:
                show_num = self.request.session[sub[0].name]['num']
            else:
                show_num = 0
            currentAdvers2 = ads_view.sortAds(list(current_advers), int(show_num))
            context.update({
                'currentAdvers': currentAdvers2,

khofo/templates/contact_us.html
{% extends 'base.html' %}
{% load staticfiles %}
<!-- custom filter module -->
{% load admin_extras %}
{% load i18n %}

{% block contact_us %}

    <!-- Contact US -->
    <link rel="stylesheet" type="text/css" href="{% static 'styles/contactus/contactus_style.css' %}">

    <!-- **** Contact Area Start **** -->
    <section class="rehomes-support-and-contact-area section-padding-80-0">
        <div class="container">
            <div class="row">
                <div class="col-12 col-md-6">
                    <div class="contact-information-area mb-80">
                        <!-- Title -->
                        <div class="support-title wow fadeInUp" data-wow-delay="200ms">
                            <h2>{% trans 'Need Help ?' %}</h2>
                        </div>

                        <!-- Support Area Content -->
                        <div class="support-area-content d-flex align-items-center wow fadeInUp" data-wow-delay="200ms">
                            <!-- Support Person Thumb -->
                            <div class="support-perosn-thumb">
                                <img src="{% static 'images/35.jpg' %}" alt="support img">
                            </div>
                            <div class="supprto-meta">
                                <h4>Azure Wilson</h4>
                                <p>Customer Realations</p>
                                <p>963.806.0919</p>
                                <p>AzureWilson@colorlib.com</p>
                            </div>
                        </div>

                        <!-- Support Area Content -->
                        <div class="support-area-content d-flex align-items-center wow fadeInUp" data-wow-delay="200ms">
                            <!-- Support Person Thumb -->
                            <div class="support-perosn-thumb">
                                <img src="{% static 'images/36.jpg' %}" alt="support img">
                            </div>
                            <div class="supprto-meta">
                                <h4>Marry Jane</h4>
                                <p>Customer Realations</p>
                                <p>963.806.0919</p>
                                <p>Marry Jane@colorlib.com</p>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-12 col-md-6">
                    <!-- Leave A Reply -->
                    <div class="rehomes-contact-form mb-80 wow fadeInUp" data-wow-delay="200ms">
                        <!-- Title -->
                        <div class="support-title">
                            <h2>{% trans 'Get In Touch' %}</h2>
                        </div>
                        <!-- Form -->
                        <form method="POST" class='support-form' enctype="multipart/form-data"
                              style="padding: 10px;border: 1px solid gray;">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-12" style="margin-bottom: 15px">
                                    {{ email_form.name }}
                                </div>
                                <div class="col-12">
                                    {{ email_form.email }}
                                </div>
                                <div class="col-12">
                                    {{ email_form.message }}
                                </div>
                                <div class="col-12" id="attach">
                                    <div class="">
                                        <span><i class="fa fa-paperclip" aria-hidden="true"></i> {% trans 'Attach File' %}</span>
                                        {{ email_form.document1 }}
                                    </div>
                                    <div class="display-hide">
                                        <span><i class="fa fa-paperclip" aria-hidden="true"></i> {% trans 'Attach File' %}</span>
                                        {{ email_form.document2 }}
                                    </div>
                                    <div class="display-hide">
                                        <span><i class="fa fa-paperclip" aria-hidden="true"></i> {% trans 'Attach File' %}</span>
                                        {{ email_form.document3 }}
                                    </div>
                                    <div class="display-hide">
                                        <span><i class="fa fa-paperclip" aria-hidden="true"></i> {% trans 'Attach File' %}</span>
                                        {{ email_form.document4 }}
                                    </div>
                                    <div class="display-hide">
                                        <span><i class="fa fa-paperclip" aria-hidden="true"></i> {% trans 'Attach File' %}</span>
                                        {{ email_form.document5 }}
                                    </div>
                                    <i id="addFile" class="btn fa fa-plus" aria-hidden="true"></i>

                                </div>
                                <div class="col-12" style="margin-top: 5px">
                                    <button type="submit" class="btn rehomes-btn">{% trans 'Send Messages' %}</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- **** Contact Area End **** -->

    <script src="{% static 'js/contact_us.js' %}"></script>
{% endblock %}

khofo/templates/finalCart.html
{% extends 'base.html' %}
{% load staticfiles %}
<!-- custom filter module -->
{% load admin_extras %}
{% load i18n %}

{% block final_cart %}
    <style>
        h5 {
            margin-top: 55px;
            font-size: 20px;
            font-weight: 300;
        }

        #co {
            display: inline-block;
            width: 20px;
            height: 20px;
            border-radius: 50%;
            margin-right: 11px;
            -webkit-transform: translateY(4px);
            -moz-transform: translateY(4px);
            -ms-transform: translateY(4px);
            -o-transform: translateY(4px);
            transform: translateY(4px);
        }

        h4 {
            font-size: 18px;
            font-weight: 400;
            color: rgba(0, 0, 0, 0.5);
        }
    </style>
    <div class="container">
        <div class="row">
            <h2>Purchases Verification</h2>
        </div>
        <div class="row" style="overflow: auto;">
            <div class="col-md-12"
                 style="min-width: 1130px;border: 5px solid goldenrod;box-shadow: 1px 1px 1px 1px gray;padding: 25px;margin-top: 40px;max-height: 400px;overflow: auto">
                <div class="row">
                    <div class="col-3">

                    </div>
                    <div class="col-3">
                        <h4>{% trans 'Name' %}</h4>
                    </div>
                    <div class="col-2">
                        <h4>{% trans 'Quantity' %}</h4>
                    </div>
                    <div class="col-2">
                        <h4>{% trans 'Price' %}</h4>
                    </div>
                    <div class="col-2">
                        <h4>{% trans 'Total' %}</h4>
                    </div>
                </div>
                <hr>
                <div id="cart2Div">
                    {% for prod in product %}
                        <div class="row">
                            <div class="col-3" style="max-height: 150px;text-align: center;">
                                <img alt="product img" src="{{ prod.0.main_img.url }}" style="max-height: 100%;max-width: 100%;">
                            </div>
                            <div class="col-3">
                                <h5>{{ prod.0.name }}</h5>
                            </div>
                            <div class="col-2">
                                <h5>{{ prod.1 }}</h5>
                            </div>
                            <div class="col-2">
                                <h5>{{ prod.0.price }}</h5>
                            </div>
                            <div class="col-2">
                                <h5>{% trans 'Total' %}</h5>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="row" style="margin-top: 30px">
            <div class="col-md-8 text-center"
                 style="border: 5px solid goldenrod;box-shadow: 1px 1px 1px 1px gray;padding: 25px;min-height: 143.3px;">
                {% if '?s=done' in request.get_full_path %}
                    <h2>{% trans 'Your Payment Was' %} <span
                            style="color: green;font-weight: bolder">{% trans 'Successful' %}</span></h2>
                    <h4 style="margin-top: 10px;">{% trans 'Your Payment Has Been Successfully Received' %}.</h4>
                    {% elif '?s=canceled' in request.get_full_path %}
                    <h2>Your Payment <span style="color: red">{% trans 'Has Not Been Processed' %}</span></h2>
                    <h4 style="margin-top: 10px;">{% trans 'There Was A Problem Processing Your Payment' %}.</h4>
                {% else %}
                    <h4 style="margin-bottom: 20px">{% trans 'Pay Using PayPal , Visa or Master Card' %}</h4>
                    {{ form.render }}
                {% endif %}
            </div>
            <div class="col-md-4"
                 style="border: 5px solid goldenrod;box-shadow: 1px 1px 1px 1px gray;padding: 25px;min-height: 143.3px;">
                <div class="order_total" style="margin-top: 20px;">
                    <div class="order_total_content text-md-center">
                        <div class="order_total_title">{% trans 'Order Total' %}:</div>
                        <div class="order_total_amount" id="tpa2">0</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br>
    <script src="{% static 'js/finalCart.js' %}"></script>
{% endblock %}

khofo/templates/head.html
{% load staticfiles %}
<title>KHOFU</title>
<meta charset="utf-8">
<meta name="description" content="Khofu store for Egyptian products, khofu">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="shortcut icon" href="{% static 'images/favicon1.png' %}">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.css"
      integrity="sha384-t4IGnnWtvYimgcRMiXD2ZD04g28Is9vYsVaHo5LcWWJkoQGmMwGg+QS0mYlhbVv3" crossorigin="anonymous">

{% if request.LANGUAGE_CODE == "ar" or request.LANGUAGE_CODE == 'ar-eg' %}
    <!-- Arabic bootstrap rtl -->
    <link rel="stylesheet" href="{% static 'styles/ar/bootstrap-rtl-4.1.1.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'styles/ar/main_styles.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'styles/ar/custom.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'styles/ar/responsive.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'styles/ar/customer_profile.css' %}">
    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Tajawal&display=swap" rel="stylesheet">
{% else %}
    <link rel="stylesheet" type="text/css" href="{% static 'styles/main_styles.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'styles/custom.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'styles/responsive.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'styles/customer_profile.css' %}">
    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
{% endif %}
<!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0/css/all.min.css"
      integrity="sha384-REHJTs1r2ErKBuJB0fCK99gCYsVjwxHrSU0N7I1zl9vZbggVJXRMsv/sLlOAGb4M" crossorigin="anonymous"> -->
<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="{% static 'plugins/OwlCarousel2-2.2.1/owl.carousel.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'plugins/OwlCarousel2-2.2.1/owl.theme.default.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'plugins/OwlCarousel2-2.2.1/animate.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'plugins/slick-1.8.0/slick.css' %}">


<!-- Flag Icons -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.4.6/css/flag-icon.min.css"
      integrity="sha384-TIJGXlVZjQ+dYPHg+oN3KvSwKHZQ4RYNPfQcWedc6mLkHd/fkZBWaf0h9Jtk022u" crossorigin="anonymous">

<!-- jQuery -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"
        integrity="sha384-vk5WoKIaW/vJyUAd9n/wmopsmNhiy+L2Z+SBxGYnUkunIxVxAv/UtMOhba/xskxh"
        crossorigin="anonymous"></script>

<script src="{% static 'js/notify.js' %}"></script>

khofo/templates/product_search_results.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load mathfilters %}
{% load my_filters %}
<!-- custom filter module -->
{% load admin_extras %}
{% load i18n %}

{% block product_search_results %}
    {% if products %}
        <div class="row" style="margin-top: 70px;">
            <div class="col-sm-12">
                <div class="row" style="margin-bottom: 28px">
                    {% for product in products %}
                        <div class="col-md-3 text-center">
                            <div class="card" style="margin: 5px auto">
                                <div class="card-body">
                                    <a class="hover_black" href="{% url 'products:product_details' product.id %}">
                                        <div class="text-center grid-product-img">
                                            <img alt="product img" class="" src="{{ product.main_img.url }}"
                                                 style="max-height: 100%; max-width: 100%;">
                                        </div>
                                    </a>
                                    {% if request.LANGUAGE_CODE == "ar" or request.LANGUAGE_CODE == 'ar-eg' %}
                                        <a class="hover_black" href="/ar/productHome/product/{{ product.id }}/">
                                            <h5 class="card-title">{{ product.name_ar }}</h5>
                                        </a>
                                        <p class="card-text" style="overflow: hidden;max-height: 15ch;">
                                            {{ product.short_description_ar }}</p>
                                        <a class="btn btn-primary"
                                           href="/ar/productHome/product/{{ product.id }}/">{% trans 'show' %}</a>

                                    {% else %}
                                        <a class="hover_black" href="/en/productHome/product/{{ product.id }}/">
                                            <h5 class="card-title">{{ product.name }}</h5>
                                        </a>
                                        <p class="card-text" style="overflow: hidden;max-height: 15ch;">
                                            {{ product.short_description }}</p>
                                        <a class="btn btn-primary"
                                           href="/en/productHome/product/{{ product.id }}/">{% trans 'show' %}</a>

                                    {% endif %}
                                </div>
                            </div>
                        </div>
                        {% if forloop.counter|divisibleby:4 %}
                            </div>
                            <div class="row">
                        {% endif %}
                    {% endfor %}
                    </div>
            </div>
        </div>

        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center">
                {% if products.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page=1">&laquo; First</a></li>
                    <li class="page-item"><a class="page-link" href="?page={{ products.previous_page_number }}">Previous</a>
                    </li>
                {% endif %}
                {% with p=request.GET.page %}
                    {% for x in products.paginator.num_pages|times %}
                        {% if x|add:1 == p|to_int %}
                            <li class="page-item active"><a class="page-link" href="?page={{ x|add:1 }}">{{ x|add:1 }}<span
                                    class="sr-only">(current)</span></a></li>
                        {% else %}
                            <li class="page-item"><a class="page-link" href="?page={{ x|add:1 }}">{{ x|add:1 }}</a></li>
                        {% endif %}
                    {% endfor %}
                {% endwith %}
                {% if products.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ products.next_page_number }}">{% trans 'Next' %}</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ products.paginator.num_pages }}">{% trans 'Last' %}&raquo;</a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    
    {% else %}
        <h1 class="text-center">No Search Results</h1>
    {% endif %}
{% endblock %}

khofo/templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>POST</h1>
    {{post}}
    <h1>GET</h1>
    {{get}}
</body>
</html>